# Generated by Django 5.1.2 on 2025-09-10 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='Nombre de jours')),
                ('mobility', models.CharField(choices=[('voiture', 'Voiture'), ('velo', 'Vélo'), ('pied', 'À pied'), ('moto', 'Moto')], max_length=10, verbose_name='Mobilité')),
                ('season', models.CharField(choices=[('ete', 'Été'), ('printemps', 'Printemps'), ('automne', 'Automne'), ('hiver', 'Hiver')], max_length=12, verbose_name='Saison')),
                ('audience', models.CharField(choices=[('famille', 'Famille'), ('seul', 'Seul'), ('groupe', 'En groupe'), ('amis', 'Entre amis')], max_length=12, verbose_name='Pour qui')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides_possedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('musee', 'Musée'), ('chateau', 'Château'), ('activite', 'Activité'), ('parc', 'Parc'), ('grotte', 'Grotte')], max_length=20, verbose_name='Catégorie')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name="Horaires d'ouverture")),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='Jour')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre de visite')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='guides_api.guide')),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254, verbose_name='Email invité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='guides_api.guide')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation de guide',
                'verbose_name_plural': 'Invitations de guide',
                'unique_together': {('guide', 'invited_email')},
            },
        ),
    ]
